# Generated by Django 4.0.1 on 2022-02-19 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField(unique=True)),
                ('amount', models.FloatField()),
                ('interest', models.FloatField()),
                ('pMode', models.CharField(max_length=30)),
                ('duration', models.IntegerField()),
                ('premium', models.FloatField(default=False)),
                ('sumAssured', models.FloatField()),
                ('withdrawn', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.IntegerField(unique=True)),
                ('amount', models.FloatField()),
                ('interest', models.FloatField()),
                ('installment', models.FloatField()),
                ('duration', models.IntegerField()),
                ('recovered', models.BooleanField(default=False)),
                ('pMode', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('role', models.CharField(choices=[('Staff', 'Staff'), ('Admin', 'Admin')], default='Staff', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='PremiumCollectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('collected', models.BooleanField(default=False)),
                ('collectedDate', models.DateField(blank=True, null=True)),
                ('collector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.user')),
                ('diposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.diposit')),
            ],
        ),
        migrations.CreateModel(
            name='LoanRecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('collected', models.BooleanField(default=False)),
                ('collectedDate', models.DateField(blank=True, null=True)),
                ('collector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.user')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.loan')),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='loanerName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.person'),
        ),
        migrations.AddField(
            model_name='diposit',
            name='dipositorName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.person'),
        ),
    ]
