# Generated by Django 4.0.1 on 2022-02-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_loan_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='outstanding',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
