# Generated by Django 4.0.1 on 2022-02-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_loanrecovery_collectionplace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diposit',
            name='sumAssured',
            field=models.FloatField(blank=True),
        ),
    ]
